[BD-24] [BB-3374] LTI Deep Linking Content Presentation - html
edx/xblock-lti-consumer pull request #132
Opened 2020-12-29 16:48 UTC by shimulch

Depends on https://github.com/edx/xblock-lti-consumer/pull/131

This PR implements the ``html`` content type for LTI Deep Linking content presentation.

**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3374

**Discussions**: N/A

**Dependencies**: None

**Screenshots**:
![Screenshot from 2020-12-29 22-45-17](https://user-images.githubusercontent.com/1010244/103299922-df920200-4a27-11eb-9a59-d44687490602.png)

**Sandbox URL**: N/A

**Merge deadline**: None

**Testing instructions**:
TBD

**Author notes and concerns**:
TBD

**Reviewers**
- [ ] @farhaanbukhsh
- [ ] edX reviewer[s] TBD

2020-12-29 16:48 UTC, edx-webhook commented
Thanks for the pull request, @shimulch! I've created [BLENDED-691](https://openedx.atlassian.net/browse/BLENDED-691) to keep track of it in Jira.   More details are on the [BD-24](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545076784/BD-24+LTI+v1.3+Improvements+Advantage+Support) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-01-09 16:51 UTC, farhaanbukhsh requested changes
This is probably a nit but I just wanted to check it.

2021-01-09 16:51 UTC, farhaanbukhsh commented on lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
> +        {'url': 'https://example.com', 'html': '<i>Hello World!</i>', 'title': 'With Title', 'text': 'With Text'},
can we add test for img tag as well?

2021-01-10 05:14 UTC, shimulch commented on lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
> +        {'url': 'https://example.com', 'html': '<i>Hello World!</i>', 'title': 'With Title', 'text': 'With Text'},
Added test for ``img`` tag.

2021-01-11 11:28 UTC, farhaanbukhsh approved these changes
👍 

- [x] I tested this: I made the entry and  changed the HTML element, I could get the content of the HTML on the view
- [x] I read through the code
- ~~[ ] I checked for accessibility issues~~
- ~~[ ] Includes documentation~~
- ~~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

2021-02-05 13:01 UTC, giovannicimolin approved these changes
:+1: 

This is an approval for the **serializer** portion of the code (commit: 611f4abf26839c4f7f174dbd9420e59d0dd122af).

- [x] I tested this: 
1. Checked out this branch.
2. Submitted a HTML component and made sure it was saved correctly.
3. Tested an invalid case (no HTML) and checked that the request failed.
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation

2021-02-16 16:29 UTC, nedbat approved these changes

2021-02-16 16:29 UTC, nedbat commented
I've merged this manually, thanks!

2021-02-16 16:29 UTC, closed without merging