refactor: Rename CourseEditLTIFieldsEnabledFlag to CourseAllowPIISharingInLTIFlag and use it for LTI1.3
edx/xblock-lti-consumer pull request #172
Opened 2021-06-16 12:35 UTC by xitij2000

This commit renames the CourseEditLTIFieldsEnabledFlag to CourseAllowPIISharingInLTIFlag since the aim is to expand its scope to all LTI-related PII sharing. It also removes the current LTI1.3 waffle flag for PII sharing.

2021-06-16 12:35 UTC, edx-webhook commented
Thanks for the pull request, @xitij2000! I've created [OSPR-5864](https://openedx.atlassian.net/browse/OSPR-5864) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-06-23 16:53 UTC, nedbat requested changes
A few typos.

2021-06-23 16:53 UTC, nedbat commented on README.rst
> +  highlight its increased scope.
```suggestion
  to highlight its increased scope.
```

2021-06-23 16:53 UTC, nedbat commented on README.rst
> +* Use `CourseAllowPIISharingInLTIFlag` for LTI1.3 in lieu of a the current
```suggestion
* Use `CourseAllowPIISharingInLTIFlag` for LTI1.3 in lieu of the current
```

2021-06-23 16:53 UTC, nedbat commented on lti_consumer/models.py
> +    will also ned to be set to actually share PII.
```suggestion
    will also need to be set to actually share PII.
```

2021-06-23 16:53 UTC, nedbat commented
@giovannicimolin any concerns?

2021-06-25 06:35 UTC, asadazam93 commented
@xitij2000 Can you please create a TNL ticket for this and add a detailed description?

2021-06-25 06:36 UTC, asadazam93 commented
@xitij2000 How do you plan to backfill data?

2021-06-25 08:24 UTC, xitij2000 commented
> @xitij2000 How do you plan to backfill data?

I'm not sure I follow. What data needs to be backfilled?

2021-06-28 12:21 UTC, asadazam93 commented
> > @xitij2000 How do you plan to backfill data?
> 
> I'm not sure I follow. What data needs to be backfilled?

You are changing the name of the model. How do you plan to fill data from the previous model into the new model?

2021-06-28 13:00 UTC, xitij2000 commented
@asadazam93 Changing the name of a model doesn't do anything to the data. The table is renamed, so the data is retained. In ths case, since the table name is also set, it won't be renamed either.

2021-07-02 13:36 UTC, awaisdar001 approved these changes
This looks good to me 👍

2021-07-02 16:21 UTC, asadazam93 approved these changes

2021-07-02 16:26 UTC, asadazam93 commented
@xitij2000 This PR is still missing a TNL ticket. Can you please create one and add to the description? Let us merge the PR after the ticket is created

2021-07-05 13:20 UTC, xitij2000 commented
@asadazam93  I've added the ticket number to the PR title.

2021-07-05 13:32 UTC, awaisdar001 commented
Thanks, @xitij2000 can this be merged?

2021-07-06 15:13 UTC, xitij2000 commented
@awaisdar001 Yes, however https://github.com/edx/edx-platform/pull/26982 will need to be adjusted right after, so I would prefer if we do this during early IST hours.

2021-07-07 14:15 UTC, asadazam93 commented
@xitij2000 Let us merge both PRs during our meeting tomorrow morning?

2021-07-07 14:19 UTC, xitij2000 commented
> @xitij2000 Let us merge both PRs during our meeting tomorrow morning?

That might not be possible. After this PR is merged, it would still be nice to run the edx-platform tests to make sure nothing is broken. That would take some time.

2021-07-07 20:15 UTC, awaisdar001 commented
> > @xitij2000 Let us merge both PRs during our meeting tomorrow morning?
> 
> That might not be possible. After this PR is merged, it would still be nice to run the edx-platform tests to make sure nothing is broken. That would take some time.

we can merge this PR in standup -- and secondly we should get in touch on Slack when the other PR in edx-platform needs to be merged.

2021-07-08 06:39 UTC, merged