feat: Added support for django32
edx/xblock-lti-consumer pull request #195
Opened 2021-08-30 09:39 UTC by Jawayria

JIRA: https://openedx.atlassian.net/browse/BOM-2697

2021-08-31 20:36 UTC, nedbat requested changes

2021-08-31 20:36 UTC, nedbat commented on .github/workflows/pypi-publish.yml
> +    types: [published]
We decided to publish to PyPI on tag creation, not GitHub releases.

2021-09-08 08:10 UTC, Jawayria commented on .github/workflows/pypi-publish.yml
> +        run: pip install setuptools wheel
Yes I guess

2021-10-06 10:44 UTC, awais786 approved these changes

2021-10-06 10:50 UTC, merged